apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eol-alert.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "eol-alert.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "eol-alert.fullname" . }}-role
  labels:
    app.kubernetes.io/name: {{ include "eol-alert.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "namespaces"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "eol-alert.fullname" . }}-rolebinding
  labels:
    app.kubernetes.io/name: {{ include "eol-alert.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "eol-alert.fullname" . }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "eol-alert.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io