apiVersion: v1
kind: Service
metadata:
  name: {{ include "eol-alert.fullname" . }}
  labels:
    {{ include "eol-alert.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "eol-alert.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}